"""Add Widget type Column

Revision ID: 147e17455c09
Revises: c55f262a41bf
Create Date: 2025-09-10 16:42:46.485239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147e17455c09'
down_revision = 'c55f262a41bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
