"""add table ownership

Revision ID: 96372a9a0398
Revises: 90ae02306dde
Create Date: 2025-09-07 22:20:44.043646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96372a9a0398'
down_revision = '90ae02306dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
