"""Add Widget Data Column

Revision ID: c55f262a41bf
Revises: e9726f1b128b
Create Date: 2025-09-10 14:54:27.340391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55f262a41bf'
down_revision = 'e9726f1b128b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_column('widget_data')

    # ### end Alembic commands ###
