services:
  app:
    build:
      context: ./backend/WhereMoney.Api
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./backend/WhereMoney.Api
          target: /app
        - action: rebuild
          path: ./backend/WhereMoney.Api/poetry.lock
    depends_on:
      - db
    environment:
      # Use the compose-provided DATABASE_URL or fall back to a value that points
      # to the `db` service. The double dollar in the db healthcheck uses an extra
      # escape so shell interpolation in this file doesn't happen during `docker-compose`.
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
    networks:
      - backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  webapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package-lock.json
    networks:
      - backend
    ports:
      - "4200:4200"
    restart: unless-stopped

  db:
    image: postgres:latest
    restart: always
    environment:
      # Provide sensible defaults for local development. These can be overridden
      # by exporting env vars or using a .env file next to this compose file.
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge

