name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.4
              
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies    
    - run: npm ci
    
    - name: Build Frontend
    - run: npm run build

    - name: Run Angular test suite
    - run: npm test

    - name: Run Lints
    - run: npm lint
